POST http://localhost:4011/api/phonebill/
Content-Type: application/json

{
    "price_plan": "sms_kick_100",
    "actions": "call, sms, call"
}

###
GET http://localhost:4011/api/price_plans
###

POST http://localhost:4011/api/price_plan/create
Content-Type: application/json

{
    "name": "Premium Pros",
    "call_cost": 1.50,
    "sms_cost": 0.50
}
###

POST http://localhost:4011/api/price_plan/update
Content-Type: application/json

{
    "name": "call 101",
    "call_cost": 10.009,
    "sms_cost": 0.98
}
###

POST http://localhost:4011/api/price_plan/delete
Content-Type: application/json

{
    "name": "sms 101"
}

